In [1]:
import numpy as np
import pandas as pd

In [2]:
rent = pd.read_csv('data/Inferential Statistics - Powai Flats Rent.csv')

In [3]:
rent.describe()

S. No.  Monthly Rent
count  200.000000    200.000000
mean   100.500000  45571.000000
std     57.879185   7457.521851
min      1.000000  30100.000000
25%     50.750000  41250.000000
50%    100.500000  44950.000000
75%    150.250000  49825.000000
max    200.000000  59800.000000

90% confidence level

In [4]:
1.65*(7457.521851/np.sqrt(200))

870.0886048286774

In [6]:
print(45571 - 870)
print(45571 + 870)

44701
46441


99% confidence level

In [7]:
err_margin = 2.58*(7457.521851/np.sqrt(200))
print(err_margin)
print(45571 - err_margin)
print(45571 + err_margin)

1360.5021820957502
44210.49781790425
46931.50218209575


99% confidence level

In [8]:
err_margin = 1.96*(7457.521851/np.sqrt(200))
print(err_margin)
print(45571 - err_margin)
print(45571 + err_margin)

1033.559797251035
44537.44020274896
46604.55979725104


In [57]:
import numpy as np 
seed=int(0)
n=int(100000000000000)
p=float(0.5)
#write your code here
if (p >=0 and p<=1):
    np.random.seed(seed)
    s = np.random.binomial(n, p, 10)
    print(s)

[50000000123289 50000002776117 49999999065652 49999996569525
 49999986841475 49999998093435 50000000075681 49999991155707
 49999998137501 49999994695014]


In [56]:
import math
n=15
print(round((12 * np.math.factorial(n-2))/np.math.factorial(n-1), 4))

0.8571


In [1]:
import re
def checkmail(email):
    temp = re.split('@|\\.', email)
    if (len(temp) != 3):
        return 'invalid'
    if ((temp[0].isalnum()) == False):
        return 'invalid'
    if ((temp[1].isalpha()) == False):
        return 'invalid' 
    if ((len(temp[2]) > 3 or len(temp[2]) < 2 or temp[2].isalpha() == False)):
        return 'invalid'
    return 'valid'
email='rbadgujar@gmail.com'
print(checkmail(email))

invalid


In [1]:
import ast,sys
import time
input_str = '[[1,2,3],[4,5],[6,7,8,9]]'
input_list = ast.literal_eval(input_str)
output = []
for i in input_list:
    if isinstance(i, list):
        output.extend(i)
%time
print(output)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 4.77 µs
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [34]:
import ast,sys
import time
input_list = [1,2,3,4,5,6,7,8,9]
for i in range(len(input_list)):
    if (input_list[i]%3 == 0):
        input_list[i] = input_list[i] * input_list[i]
print(input_list)        

[1, 2, 9, 4, 5, 36, 7, 8, 81]


In [2]:
import math
n=input()
n = int(n)
def sum_of_n(i, p):
    if p == 0:
        return i;
    else:
        return i * math.pow(10, p) + sum_of_n(i, p-1)

output = 0
for i in range(4):
    output = output + sum_of_n(n, i)
print(output)


1234567
1523455678.0


In [3]:
string = 'cccaaaaabdddffgfhhhzzzzz'
#string = 'ddddaacccb'
n = 4
frequency = {}
output = []
for i in set(string):
    count = string.count(i)
    if (count in frequency):
        l = frequency[count]
        l.append(i)
        l.sort()
    else:
        frequency[count] = [i]

print(frequency)
print(sorted(frequency, reverse=True))

i = n
ind = 0
while i > 0:
    l = frequency[sorted(frequency, reverse=True)[ind]]
    ind = ind+1
    if (len(l) == 1):
        output.extend(l)
        output.sort()
        i = i-1;
    else:
        index = 0
        if ((len(l) > i) == True):
            index = i
        else:
            index = len(l)
        output.extend(l[0:index])
        i = i-len(l);

print(output)

{1: ['b', 'g'], 5: ['a', 'z'], 3: ['c', 'd', 'f', 'h']}
[5, 3, 1]
['a', 'z', 'c', 'd']


In [10]:
input_str = 'cccaaaabddffgfhhhzzzzz'
n = 4
frequency = {}
output = []
for i in set(input_str):
    count = input_str.count(i)
    if (count in frequency):
        l = frequency[count]
        l.append(i)
        l.sort()
    else:
        frequency[count] = [i]

print(frequency)
print(sorted(frequency, reverse=True))
for i in sorted(frequency, reverse=True):
    l = frequency[i]
    output.extend(l)
    
print(sorted(output[0:n]))

{1: ['b', 'g'], 5: ['z'], 4: ['a'], 2: ['d'], 3: ['c', 'f', 'h']}
[5, 4, 3, 2, 1]
['a', 'c', 'f', 'z']


In [4]:
string='cccaaaabddffgfhhhzzzzz'
n=4
import collections
out=[collections.Counter(string).most_common(i+1)[i][0] for i in range(n)]
out.sort()
print(out)

['a', 'c', 'f', 'z']


In [3]:
import numpy as np
x = 3
y = 4
l = [i+j/2 for i in range(x) for j in range(y)]
arr = np.array(l)
print(np.reshape(arr, (x,y), order='C'))

[[0.  0.5 1.  1.5]
 [1.  1.5 2.  2.5]
 [2.  2.5 3.  3.5]]
